name: ble
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.17
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  flutter_dotenv: ^5.2.1
  shared_preferences: ^2.5.2
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  google_fonts: ^6.2.1
  gauge_indicator: ^0.4.3
  syncfusion_flutter_gauges: ^28.2.6
  timeago: ^3.2.2
  flutter_blue_plus: ^1.35.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  riverpod_generator: ^2.6.4
  build_runner: ^2.4.15
  custom_lint: ^0.7.3
  riverpod_lint: ^2.6.4
  freezed: ^2.5.8
  json_serializable: ^6.9.4

flutter:
  uses-material-design: true
  assets:
    - assets/svgs/
    - assets/pngs/
#    - .env
